### ISSUE TITLE
Missing module during build

### ISSUE THREAD

**Issue by goudine** [boundlessgeo/schema#28]
When building with `sh script/java.sh` , it succeeds but an error message appears at the beginning of the build:
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'rx'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/agoudine/repos/schema/script/index.js:6:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
mv: rename Actions.java to ./java/src/main/java/com/boundlessgeo/schema/Actions.java: No such file or directory
script/java.sh: line 5: protoc: command not found
script/java.sh: line 6: protoc: command not found
```

Same message occurred during `node script/index.js objc`.

**Comment by goudine** [comment]
Master branch is building, however I still see the error during a Java build

**Comment by goudine** [comment]
Build now works without any error
